### ISSUE TITLE
Upgrade Rust Core's version.

### ISSUE THREAD

**Issue by cardosoOReis** [mcmah309/anyhow#2]
Could you please upgrade the rust core's version 🥺?

**Comment by mcmah309** [comment]
Sure, I'll get around to that today. Does adding `rust_core: ^0.3.6` to your `pubspec.yaml` work in the meantime

**Comment by mcmah309** [comment]
Weird, `dart pub upgrade` should upgrade transitive dependencies too. I ran a little test to check. On a side note, I wouldn't worry about pulling in `rust_core` since darts tree shaking will remove any code you do not use. anyhow (punny), I just updated the min version to `0.3.6` for ya.
