### ISSUE TITLE
Allow for existing Stack Traces to be added with a new anyhow error.

### ISSUE THREAD

**Issue by cds-reis** [mcmah309/anyhow#4]
A lot of times in Dart code, when you are handling exceptions, you get a Stack Trace with you:
```dart
///
} catch (e, st) {
///
```
So, when you are using it with the anyhow package, you end up losing the original Stack Trace for the new one create by the functions `anyhow` and `bail`.
I propose a way to preserve the existing stack trace, with something like this:

Changing the `bail`and `anyhow` functions signature to:

`Error anyhow<S>(Object err, [StackTrace? stackTrace])`;
`Err<S> bail<S>(Object err, [StackTrace? stackTrace])`.

This would lead to adding this functionality of preserving the stack trace while maintaining backward compatibility.

So you could write
```dart
} catch (e, st) {
  return bail(e, st);
}
```

Then, both functions would check if the errors should be captured with a stack trace, and decide if it adds it or not.

**Comment by mcmah309** [comment]
Good idea. I added this in [2.0.0-dev.7](https://pub.dev/packages/anyhow/versions/2.0.0-dev.7)
